### ISSUE TITLE
Use in Commercial Software

### ISSUE THREAD

**Issue by hrishiballal** [GEOF-OSGL/Leaflet.EdgeScaleBar#1]
Hello this is a great plugin and idea, however because it is GPL 3, I cannot use it in Geodesignhub. Can I request humbly that you consider re-licensing it to a more permissive license (e.g. Apache 2 or MIT). I am happy to make a small monetary contribution as a way of saying thanks. It is not a problem if you cannot change it, I appreciate your effort, just wanted to make a request.

**Comment by dtutic** [comment]
Dear Hrishikesh,


I would rather not change the license for this published Github code.


I have other and a more developed version with additional options (visualizations of scales, deformations, lines of graphical scale across whole map etc.), and that one is not published yet. I can send it to you to evaluate it but not before Dec 25 (it is on another computer). I will be glad to drink a beer or two if you find it useful for your project 😊


Hope this option will work for you too.

Kind regards,

Dražen Tutić


________________________________

**Comment by hrishiballal** [comment]
Hello Dražen, 
🙏 Thank you for this. Let me drop you a email on your email address.

**Comment by dtutic** [comment]
My email is dtutic@geof.hr<mailto:dtutic@geof.hr>

---- Hrishikesh Ballal wrote ----


Hello Dražen,
🙏 Thank you for this. Let me drop you a email on your email address.
