### ISSUE TITLE
How to remove EdgeScaleBar 

### ISSUE THREAD

**Issue by gaveen5555** [GEOF-OSGL/Leaflet.EdgeScaleBar#2]
I can add the scale bar as follows 
L.edgeScaleBar().addTo(map);

But if i wanted to remove it programically, how do i do it?

**Comment by dtutic** [comment]
Store object in variable and use it later with map.removeLayer function, e.g.

var edgeSB = L.edgeScaleBar().addTo(map);

put where you need to remove it:

map.removeLayer(edgeSB);
